source "http://rubygems.org"

gem 'c2po'

gem 'guard'
gem 'rb-inotify', :require => false
gem 'rb-fsevent', :require => false
gem 'rb-fchange', :require => false

gem 'guard-livereload'
gem 'guard-webrick'


